name: build-test-XIOS

on: [push, pull_request]

jobs:
  build_test:
    name: build XIOS and run tests
    runs-on: ubuntu-latest
    steps:
      # Check out repository branch
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
            sudo apt update
            sudo apt -yq install subversion
            sudo apt -yq install $(<dependencies)
      - name: clone and build XIOS
        run: |
          svn co http://forge.ipsl.jussieu.fr/ioserver/svn/XIOS2/trunk XIOS2
          cp arch/* XIOS2/arch/
          cd XIOS2
          ./make_xios --job 2 --arch GCC_LINUX_APT
          cd ..
      - name: run generic
        run: |
          cd XIOS2/generic_testcase
          ln -s ../bin/generic_testcase.exe
          ln -s ../bin/xios_server.exe
          sed -i 's/nb_proc_atm=4/nb_proc_atm=1/g' param.def
          mpiexec -n 1 ./generic_testcase.exe : -n 1 ./xios_server.exe
          cd ../..
      - name: run resample example
        run: |
          . arch/arch-GCC_LINUX_APT.env
          . arch/arch-GCC_LINUX_APT.path
          export XIOS_BINDIR=$PWD/XIOS2/bin
          export XIOS_INCDIR=$PWD/XIOS2/inc
          export XIOS_LIBDIR=$PWD/XIOS2/lib

          python3 -m unittest discover -v -s xios_examples
